# Query specific entity types by their UUID value.
query Node($uuid: ID!) {
    node(id: $uuid) {
        ...FragmentNodeUnion
    }
}

fragment FragmentPageInfo on ConnectionPageInfo {
    hasNextPage
    endCursor
}

fragment AllNodeInterface on NodeInterface {
    id
    path
    changed {
        time
    }
}

query AllNodes($first: Int = 1000, $nodeStanfordCourses: Cursor, $nodeStanfordEventSeriesItems: Cursor, $nodeStanfordEvents: Cursor, $nodeStanfordNewsItems: Cursor, $nodeStanfordPages: Cursor, $nodeStanfordPeople: Cursor, $nodeStanfordPolicies: Cursor, $nodeStanfordPublications: Cursor) {
    nodeStanfordCourses(first: $first, after: $nodeStanfordCourses, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordEventSeriesItems(first: $first, after: $nodeStanfordEventSeriesItems, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordEvents(first: $first, after: $nodeStanfordEvents, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordNewsItems(first: $first, after: $nodeStanfordNewsItems, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordPages(first: $first, after: $nodeStanfordPages, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordPeople(first: $first, after: $nodeStanfordPeople, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordPolicies(first: $first, after: $nodeStanfordPolicies, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
    nodeStanfordPublications(first: $first, after: $nodeStanfordPublications, sortKey: CREATED_AT) {
        nodes {
            ...AllNodeInterface
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query Courses($first: Int = 1000, $after: Cursor) {
    nodeStanfordCourses(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordCourse
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query EventSeries($first: Int = 1000, $after: Cursor) {
    nodeStanfordEventSeriesItems(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordEventSeries
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query Events($first: Int = 1000, $after: Cursor) {
    nodeStanfordEvents(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordEvent
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query News($first: Int = 1000, $after: Cursor) {
    nodeStanfordNewsItems(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordNews
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query BasicPages($first: Int = 1000, $after: Cursor) {
    nodeStanfordPages(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordPage
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query People($first: Int = 1000, $after: Cursor) {
    nodeStanfordPeople(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordPerson
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query Policies($first: Int = 1000, $after: Cursor) {
    nodeStanfordPolicies(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordPolicy
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}

query Publications($first: Int = 1000, $after: Cursor) {
    nodeStanfordPublications(first: $first, after: $after, sortKey: CREATED_AT) {
        nodes {
            ...FragmentNodeStanfordPublication
        }
        pageInfo {
            ...FragmentPageInfo
        }
    }
}


query Media($uuid: ID!) {
    media(id: $uuid) {
        ...FragmentMediaUnion
    }
}

query Term($uuid: ID!) {
    term(id: $uuid) {
        ...FragmentTermInterface
    }
}

query Paragraph($uuid: ID!) {
    paragraph(id: $uuid) {
        ...FragmentParagraphUnion
    }
}

query ConfigPages {
    stanfordBasicSiteSettings(first: 1) {
        nodes {
            __typename
            id
            suGoogleAnalytics
            suSiteAlgolia
            suSiteAlgoliaId
            suSiteAlgoliaIndex
            suSiteAlgoliaSearch
            suSiteDropdowns
            suSiteMenuLevels
            suSiteName
            suSiteNobots
        }
    }
    stanfordGlobalMessages(first: 1) {
        nodes {
            __typename
            id
            suGlobalMsgEnabled
            suGlobalMsgHeader
            suGlobalMsgLabel
            suGlobalMsgLink {
                title
                url
            }
            suGlobalMsgMessage {
                processed
            }
            suGlobalMsgType
        }
    }
    stanfordLocalFooters(first: 1) {
        nodes {
            __typename
            id
            suFooterEnabled
            suLocalFootAction {
                title
                url
            }
            suLocalFootAddress {
                additionalName
                addressLine1
                addressLine2
                administrativeArea
                country {
                    code
                    name
                }
                dependentLocality
                familyName
                givenName
                langcode
                locality
                organization
                postalCode
                sortingCode
            }
            suLocalFootFButton
            suLocalFootFIntro {
                processed
            }
            suLocalFootFMethod
            suLocalFootFUrl {
                url
                title
            }
            suLocalFootLine1
            suLocalFootLine4
            suLocalFootLine2
            suLocalFootLine3
            suLocalFootLine5
            suLocalFootLocImg {
                alt
                height
                url
                width
            }
            suLocalFootLocLink {
                title
                url
            }
            suLocalFootLocOp
            suLocalFootPrCo {
                processed
            }
            suLocalFootPrimary {
                title
                url
            }
            suLocalFootPrimeH
            suLocalFootSeCo {
                processed
            }
            suLocalFootSecond {
                title
                url
            }
            suLocalFootSecondH
            suLocalFootSocial {
                title
                url
            }
            suLocalFootSunetT
            suLocalFootTr2Co {
                processed
            }
            suLocalFootTrCo {
                processed
            }
            suLocalFootUseLoc
            suLocalFootUseLogo
        }
    }
    stanfordSuperFooters(first: 1) {
        nodes {
            __typename
            id
            suSuperFootEnabled
            suSuperFootIntranet {
                title
                url
            }
            suSuperFootLink {
                title
                url
            }
            suSuperFootText {
                processed
            }
            suSuperFootTitle
        }
    }
    lockupSettings(first: 1) {
        nodes {
            __typename
            id
            suLine1
            suLine2
            suLine3
            suLine4
            suLine5
            suLockupEnabled
            suLockupOptions
            suUploadLogoImage {
                alt
                height
                url
                width
            }
            suUseThemeLogo
        }
    }
}