
fragment FragmentNodeInterface on NodeInterface {
    __typename
    id
    title
    status
    path
    changed {
        ...FragmentDateTime
    }
    created {
        ...FragmentDateTime
    }
}

fragment FragmentNodeStanfordPage on NodeStanfordPage {
    ...FragmentNodeInterface
    layoutSelection {
        id
    }
    suBasicPageType {
        ...FragmentTermInterface
    }
    suPageBanner {
        ...FragmentParagraphStanfordBanner
        ...FragmentParagraphStanfordPageTitleBanner
    }
    suPageComponents {
        ...FragmentParagraphUnion
    }
    suPageDescription
    suPageImage {
        ...FragmentMediaUnion
    }
}

fragment FragmentNodeStanfordCourse on NodeStanfordCourse {
    ...FragmentNodeInterface
    body {
        ...FragmentTextSummary
    }
    suCourseAcademicYear
    suCourseCode
    suCourseId
    suCourseInstructors
    suCourseLink {
        url
        title
    }
    suCourseQuarters {
        ...FragmentTermInterface
    }
    suCourseSectionUnits
    suCourseSubject {
        ...FragmentTermInterface
    }
    suCourseTags {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordEvent on NodeStanfordEvent {
    ...FragmentNodeInterface
    body {
        ...FragmentTextSummary
    }
    suEventAltLoc
    suEventAudience {
        ...FragmentTermInterface
    }
    suEventComponents {
        ...FragmentParagraphUnion
    }
    suEventContactInfo
    suEventCta {
        url
        title
    }
    suEventDateTime {
        ...FragmentSmartDateType
    }
    suEventDek
    suEventEmail
    suEventGroups {
        ...FragmentTermInterface
    }
    suEventKeywords {
        ...FragmentTermInterface
    }
    suEventLocation {
        ...FragmentAddressType
    }
    suEventMapLink {
        url
        title
    }
    suEventSchedule {
        ...FragmentParagraphStanfordSchedule
    }
    suEventSource {
        url
        title
    }
    suEventSponsor
    suEventSubheadline
    suEventSubject {
        ...FragmentTermInterface
    }
    suEventTelephone
    suEventType {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordEventSeries on NodeStanfordEventSeries {
    ...FragmentNodeInterface
    suEventSeriesComponents {
        ...FragmentParagraphUnion
    }
    suEventSeriesDek
    suEventSeriesEvent {
        ...FragmentNodeStanfordEventTeaser
    }
    suEventSeriesSubheadline
    suEventSeriesType {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordNews on NodeStanfordNews {
    ...FragmentNodeInterface
    suNewsBanner {
        ...FragmentMediaUnion
    }
    suNewsBannerMediaCaption
    suNewsByline
    suNewsComponents {
        ...FragmentParagraphUnion
    }
    suNewsDek
    suNewsFeaturedMedia {
        ...FragmentMediaUnion
    }
    suNewsHideSocial
    suNewsPublishingDate {
        ...FragmentDateTime
    }
    suNewsSource {
        url
        title
    }
    suNewsTopics {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordPerson on NodeStanfordPerson {
    ...FragmentNodeInterface
    body {
        ...FragmentTextSummary
    }
    suPersonAcademicAppt
    suPersonAdminAppts
    suPersonAffiliations {
        url
        title
    }
    suPersonComponents {
        ...FragmentParagraphUnion
    }
    suPersonEducation
    suPersonEmail
    suPersonFax
    suPersonFirstName
    suPersonFullTitle
    suPersonLastName
    suPersonLinks {
        url
        title
    }
    suPersonLocationAddress {
        ...FragmentText
    }
    suPersonLocationName
    suPersonMailCode
    suPersonMapUrl {
        url
        title
    }
    suPersonMobilePhone
    suPersonPhoto {
        ...FragmentMediaImage
    }
    suPersonProfileLink {
        url
        title
    }
    suPersonPronouns
    suPersonResearch {
        ...FragmentText
    }
    suPersonResearchInterests
    suPersonScholarlyInterests {
        ...FragmentText
    }
    suPersonShortTitle
    suPersonTelephone
    suPersonTypeGroup {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeStanfordPolicy on NodeStanfordPolicy {
    ...FragmentNodeInterface
    body {
        ...FragmentTextSummary
    }
    suPolicyAuthority
    suPolicyAutoPrefix
    suPolicyChangelog {
        ...FragmentSuPolicyLog
    }
    suPolicyChapter
    suPolicyEffective {
        ...FragmentDateTime
    }
    suPolicyPolicyNum
    suPolicyRelated {
        ... on NodeInterface {
            id
            path
        }
    }
    suPolicySubchapter
    suPolicyTitle
    suPolicyUpdated {
        ...FragmentDateTime
    }
    book {
        id
        title
        url
        expanded
        children {
            id
            title
            url
            expanded
            children {
                id
                title
                url
                expanded
                children {
                    id
                    title
                    url
                    expanded
                    children {
                        id
                        title
                        url
                        expanded
                        children {
                            id
                            title
                            url
                            expanded
                        }
                    }
                }
            }
        }
    }
}

fragment FragmentNodeStanfordPublication on NodeStanfordPublication {
    ...FragmentNodeInterface
    suPublicationAuthorRef {
        ...FragmentNodeStanfordPersonTeaser
    }
    suPublicationComponents {
        ...FragmentParagraphUnion
    }
    suPublicationCta {
        url
        title
    }
    suPublicationImage {
        ...FragmentMediaImage
    }
    suPublicationTopics {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeUnion on NodeUnion {
    ...FragmentNodeInterface
    ...FragmentNodeStanfordCourse
    ...FragmentNodeStanfordEvent
    ...FragmentNodeStanfordEventSeries
    ...FragmentNodeStanfordNews
    ...FragmentNodeStanfordPage
    ...FragmentNodeStanfordPerson
    ...FragmentNodeStanfordPolicy
    ...FragmentNodeStanfordPublication
}

fragment FragmentNodeStanfordCourseTeaser on NodeStanfordCourse {
    ...FragmentNodeInterface
    suCourseSubject {
        ...FragmentTermInterface
    }
    suCourseAcademicYear
    suCourseCode
    suCourseQuarters {
        ...FragmentTermInterface
    }
    suCourseInstructors
    body {
        processed
    }
}

fragment FragmentNodeStanfordEventTeaser on NodeStanfordEvent {
    ...FragmentNodeInterface
    suEventAltLoc
    suEventSubheadline
    suEventDek
    suEventAltLoc
    suEventLocation {
        ...FragmentAddressType
    }
    suEventDateTime {
        ...FragmentSmartDateType
    }
    suEventType {
        ...FragmentTermInterface
    }
    suEventSource {
        url
        title
    }
}

fragment FragmentNodeStanfordEventSeriesTeaser on NodeStanfordEventSeries {
    ...FragmentNodeInterface
    suEventSeriesDek
}

fragment FragmentNodeStanfordNewsTeaser on NodeStanfordNews {
    ...FragmentNodeInterface
    suNewsDek
    suNewsFeaturedMedia {
        ...FragmentMediaImage
    }
    suNewsTopics {
        ...FragmentTermInterface
    }
    suNewsPublishingDate {
        ...FragmentDateTime
    }
    suNewsSource {
        url
    }
}

fragment FragmentNodeStanfordPageTeaser on NodeStanfordPage {
    ...FragmentNodeInterface
    suPageDescription
    suPageImage {
        ...FragmentMediaImage
    }
    suPageBanner {
        ... on ParagraphStanfordBanner {
            suBannerImage {
                ...FragmentMediaImage
            }
        }
        ...FragmentParagraphStanfordPageTitleBanner
    }
}

fragment FragmentNodeStanfordPersonTeaser on NodeStanfordPerson {
    ...FragmentNodeInterface
    suPersonPhoto {
        ...FragmentMediaImage
    }
    suPersonFullTitle
    suPersonShortTitle
}

fragment FragmentNodeStanfordPolicyTeaser on NodeStanfordPolicy {
    ...FragmentNodeInterface
    body {
        ...FragmentTextSummary
    }
    suPolicyUpdated {
        ...FragmentDateTime
    }
}

fragment FragmentNodeStanfordPublicationTeaser on NodeStanfordPublication {
    ...FragmentNodeInterface
    suPublicationTopics {
        ...FragmentTermInterface
    }
}

fragment FragmentNodeTeaserUnion on NodeUnion {
    ...FragmentNodeInterface
    ...FragmentNodeStanfordCourseTeaser
    ...FragmentNodeStanfordEventTeaser
    ...FragmentNodeStanfordEventSeriesTeaser
    ...FragmentNodeStanfordNewsTeaser
    ...FragmentNodeStanfordPageTeaser
    ...FragmentNodeStanfordPersonTeaser
    ...FragmentNodeStanfordPolicyTeaser
    ...FragmentNodeStanfordPublicationTeaser
}
