# Each of the view queries.

fragment FragmentViewPageInfo on ViewPageInfo {
    page
    total
}

query stanfordBasicPages($filters: StanfordBasicPagesContextualFilterInput, $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordBasicPages(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordPageTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordBasicPagesCards($filters: StanfordBasicPagesCardsContextualFilterInput, $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordBasicPagesCards(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordPageTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordCourses($filters: StanfordCoursesContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordCourses(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordCourse
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordCoursesCardGrid($filters: StanfordCoursesCardGridContextualFilterInput, $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordCoursesCardGrid(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordCourse
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordEventsCardGrid($filters: StanfordEventsCardGridContextualFilterInput, $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordEventsCardGrid(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordEventTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordEvents($filters: StanfordEventsContextualFilterInput, $pageSize: Int, $page: Int = -1, $offset: Int) {
    stanfordEvents(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordEventTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordEventsPastEvents($filters: StanfordEventsPastEventsContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordEventsPastEvents(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordEventTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordNewsDefaultList($filters: StanfordNewsDefaultListContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordNewsDefaultList(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordNewsTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordNewsCardGrid($filters: StanfordNewsCardGridContextualFilterInput, $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordNewsCardGrid(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordNewsTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordPerson($filters: StanfordPersonContextualFilterInput, $pageSize: Int, $page: Int = -1, $offset: Int) {
    stanfordPerson(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordPersonTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordPublicationsApa($filters: StanfordPublicationsApaContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordPublicationsApa(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordPublicationTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordPublicationsChicago($filters: StanfordPublicationsChicagoContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordPublicationsChicago(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordPublicationTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordSharedTags($filters: StanfordSharedTagsContextualFilterInput, $pageSize: Int, $page: Int = 3, $offset: Int) {
    stanfordSharedTags(contextualFilter: $filters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeTeaserUnion
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}
