# Each of the view queries.

fragment FragmentViewPageInfo on ViewPageInfo {
    page
    total
}

fragment FragmentView on View {
    pageInfo {
        ...FragmentViewPageInfo
    }
}

query stanfordBasicPages($contextualFilters: StanfordBasicPagesContextualFilterInput, $sortKey: StanfordBasicPagesSortKeys, $sortDir: SortDirection $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordBasicPages(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset, sortKey: $sortKey, sortDir: $sortDir) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordPageTeaser
        }
    }
}

query stanfordCourses($contextualFilters: StanfordCoursesContextualFilterInput, $filter: StanfordCoursesFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordCourses(contextualFilter: $contextualFilters, filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordCourse
        }
    }
}

query stanfordEvents($contextualFilters: StanfordEventsContextualFilterInput, $pageSize: Int, $page: Int = -1, $offset: Int) {
    stanfordEvents(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset, sortKey: START_TIME) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordEventTeaser
        }
    }
}

query stanfordEventsPastEvents($contextualFilters: StanfordEventsPastEventsContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordEventsPastEvents(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset, sortKey: START_TIME) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordEventTeaser
        }
    }
}

query stanfordMedia($contextualFilters: StanfordMediaContextualFilterInput, $filter: StanfordMediaFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordMedia(contextualFilter: $contextualFilters, filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordMediaTeaser
        }
    }
}

query stanfordNews($contextualFilters: StanfordNewsContextualFilterInput, $filter: StanfordNewsFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordNews(contextualFilter: $contextualFilters, filter: $filter pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordNewsTeaser
        }
    }
}

query stanfordOpportunities($contextualFilters: StanfordOpportunitiesContextualFilterInput, $filter: StanfordOpportunitiesFilterInput, $sortKey: StanfordOpportunitiesSortKeys, $pageSize: Int = 3, $page: Int $offset: Int) {
    stanfordOpportunities(contextualFilter: $contextualFilters, filter: $filter, pageSize: $pageSize, page: $page, offset: $offset, sortKey: $sortKey) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordOpportunityTeaser
        }
    }
}

query stanfordPerson($contextualFilters: StanfordPersonContextualFilterInput, $filter: StanfordPersonFilterInput, $pageSize: Int, $page: Int = -1, $offset: Int) {
    stanfordPerson(contextualFilter: $contextualFilters, filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordPersonTeaser
        }
    }
}

query stanfordPublications($contextualFilters: StanfordPublicationsContextualFilterInput, $filter: StanfordPublicationsFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordPublications(contextualFilter: $contextualFilters, filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordPublicationTeaser
        }
    }
}

query stanfordSharedTags($contextualFilters: StanfordSharedTagsContextualFilterInput, $pageSize: Int = 3, $page: Int $offset: Int) {
    stanfordSharedTags(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeTeaserUnion
        }
    }
}

query search($filter: SearchFilterInput = {key: ""}, $pageSize: Int = 3, $page: Int $offset: Int) {
    search(filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        ...FragmentView
        results {
            ...FragmentNodeInterface
            ...FragmentNodeTeaserUnion
        }
    }
}

